global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['dbexporter:9104']
<<<if{{{rabbitmq/enabled}}}>>>
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmqexporter:9419']
<<<endif>>>
