<<<if{{{search/elasticsearch/dashboard/enabled}}}>>>
  kibana:
    platform: linux/x86_64
    image: {{{search/elasticsearch/dashboard/repository}}}:{{{search/elasticsearch/version}}}
    environment:
      SERVER_BASEPATH: /kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "{{{nginx/port/project+3}}}:5601"
    depends_on:
      - elasticsearch
<<<endif>>>
    <<<if{{{search/elasticsearch/dashboard/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>