<<<if{{{search/opensearch/enabled}}}>>>
  opensearch:
    build:
      context: ctx
      dockerfile: opensearch.Dockerfile
    deploy:
      resources:
        limits:
          memory: 2512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      OPENSEARCH_DISCOVERY_TYPE: 'single-node'
      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      DISABLE_SECURITY_PLUGIN: 'true'
      ES_JAVA_OPTS: '-Xms800m -Xmx800m'
    volumes:
      - opensearch_vlm_{{{search/opensearch/version}}}:/usr/share/opensearch/data
<<<endif>>>
    <<<if{{{search/opensearch/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>